title: Mark M. Erjavec - Entrepreneur in Finance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://markerjavec.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
    - jekyll-feed

sass:
    sass_dir: assets/css/_sass

defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: blog
          permalink: /blog/:year-:month-:day-:title.html
          published: false

privacy:
    hubspot: true

    address:
        name: Mark M. Erjavec
    street: "1041 Grand Ave #300"
    city: St. Paul
    state: Minnesota
    zip: 55105
    country: United States
    phone: +1 (612) 870-2812
    domain: https://markerjavec.com
